import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-3pl-warehouse-invoice-sla-recovery",
  "engine": "recovery",
  "title": "3PL Warehouse Invoice & SLA Recovery",
  "shortTitle": "3PL Recovery OS",
  "tagline": "Audit storage, handling, value-added services, inventory accuracy, and fulfillment commitments",
  "industry": "Outsourced Warehousing Financial Assurance",
  "uiPort": 4577,
  "apiPort": 5577,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "Unsupported 3PL charges and failed service commitments converted into credits and improved unit economics",
  "valueNarrative": "Reconcile warehouse agreements, inventory, receipts, orders, labor, services, invoices, SLA events, losses, and credits.",
  "calculation": {
    "actualKey": "billedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "3PL Billed Amount",
    "expectedLabel": "Activity-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Warehouse activity, inventory, contract rate, and SLA evidence indicate recoverable 3PL charges or credits.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("3pl-contract-and-rate-library","3RO01","3PL contract and rate library","Reconcile 3pl contract and rate library using 3PL contracts, rate cards, inventory snapshots, receipts, putaway, storage positions, picks, packs, labor, value-added services, orders, invoices, and SLAs.","Produce a governed 3pl contract and rate library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerFacility","3PL / Facility","text","Atlas Fulfillment / DFW-04"],["caseReference","3PL contract and rate library Reference","text","3RO01-2026-001"],["billedAmount","3PL Billed Amount","currency",924000],["supportedAmount","Activity-Supported Amount","currency",811500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Ecommerce fulfillment center","Cold-storage warehouse","Retail distribution center","Spare parts 3PL","Omnichannel facility"]}),
feature("facility-and-account-registry","3RO02","Facility and account registry","Reconcile facility and account registry using 3PL contracts, rate cards, inventory snapshots, receipts, putaway, storage positions, picks, packs, labor, value-added services, orders, invoices, and SLAs.","Produce a governed facility and account registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerFacility","3PL / Facility","text","Atlas Fulfillment / DFW-04"],["caseReference","Facility and account registry Reference","text","3RO02-2026-001"],["billedAmount","3PL Billed Amount","currency",924000],["supportedAmount","Activity-Supported Amount","currency",811500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Ecommerce fulfillment center","Cold-storage warehouse","Retail distribution center","Spare parts 3PL","Omnichannel facility"]}),
feature("inventory-snapshot-ingestion","3RO03","Inventory snapshot ingestion","Reconcile inventory snapshot ingestion using 3PL contracts, rate cards, inventory snapshots, receipts, putaway, storage positions, picks, packs, labor, value-added services, orders, invoices, and SLAs.","Produce a governed inventory snapshot ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerFacility","3PL / Facility","text","Atlas Fulfillment / DFW-04"],["caseReference","Inventory snapshot ingestion Reference","text","3RO03-2026-001"],["billedAmount","3PL Billed Amount","currency",924000],["supportedAmount","Activity-Supported Amount","currency",811500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Ecommerce fulfillment center","Cold-storage warehouse","Retail distribution center","Spare parts 3PL","Omnichannel facility"]}),
feature("receipt-and-putaway-reconciliation","3RO04","Receipt and putaway reconciliation","Reconcile receipt and putaway reconciliation using 3PL contracts, rate cards, inventory snapshots, receipts, putaway, storage positions, picks, packs, labor, value-added services, orders, invoices, and SLAs.","Produce a governed receipt and putaway reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerFacility","3PL / Facility","text","Atlas Fulfillment / DFW-04"],["caseReference","Receipt and putaway reconciliation Reference","text","3RO04-2026-001"],["billedAmount","3PL Billed Amount","currency",924000],["supportedAmount","Activity-Supported Amount","currency",811500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Ecommerce fulfillment center","Cold-storage warehouse","Retail distribution center","Spare parts 3PL","Omnichannel facility"]}),
feature("storage-position-recalculation","3RO05","Storage position recalculation","Reconcile storage position recalculation using 3PL contracts, rate cards, inventory snapshots, receipts, putaway, storage positions, picks, packs, labor, value-added services, orders, invoices, and SLAs.","Produce a governed storage position recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerFacility","3PL / Facility","text","Atlas Fulfillment / DFW-04"],["caseReference","Storage position recalculation Reference","text","3RO05-2026-001"],["billedAmount","3PL Billed Amount","currency",924000],["supportedAmount","Activity-Supported Amount","currency",811500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Ecommerce fulfillment center","Cold-storage warehouse","Retail distribution center","Spare parts 3PL","Omnichannel facility"]}),
feature("pick-pack-and-handling-audit","3RO06","Pick pack and handling audit","Reconcile pick pack and handling audit using 3PL contracts, rate cards, inventory snapshots, receipts, putaway, storage positions, picks, packs, labor, value-added services, orders, invoices, and SLAs.","Produce a governed pick pack and handling audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerFacility","3PL / Facility","text","Atlas Fulfillment / DFW-04"],["caseReference","Pick pack and handling audit Reference","text","3RO06-2026-001"],["billedAmount","3PL Billed Amount","currency",924000],["supportedAmount","Activity-Supported Amount","currency",811500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Ecommerce fulfillment center","Cold-storage warehouse","Retail distribution center","Spare parts 3PL","Omnichannel facility"]}),
feature("value-added-service-validation","3RO07","Value-added service validation","Reconcile value-added service validation using 3PL contracts, rate cards, inventory snapshots, receipts, putaway, storage positions, picks, packs, labor, value-added services, orders, invoices, and SLAs.","Produce a governed value-added service validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerFacility","3PL / Facility","text","Atlas Fulfillment / DFW-04"],["caseReference","Value-added service validation Reference","text","3RO07-2026-001"],["billedAmount","3PL Billed Amount","currency",924000],["supportedAmount","Activity-Supported Amount","currency",811500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Ecommerce fulfillment center","Cold-storage warehouse","Retail distribution center","Spare parts 3PL","Omnichannel facility"]}),
feature("labor-charge-audit","3RO08","Labor charge audit","Reconcile labor charge audit using 3PL contracts, rate cards, inventory snapshots, receipts, putaway, storage positions, picks, packs, labor, value-added services, orders, invoices, and SLAs.","Produce a governed labor charge audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerFacility","3PL / Facility","text","Atlas Fulfillment / DFW-04"],["caseReference","Labor charge audit Reference","text","3RO08-2026-001"],["billedAmount","3PL Billed Amount","currency",924000],["supportedAmount","Activity-Supported Amount","currency",811500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Ecommerce fulfillment center","Cold-storage warehouse","Retail distribution center","Spare parts 3PL","Omnichannel facility"]}),
feature("minimum-commitment-calculation","3RO09","Minimum commitment calculation","Reconcile minimum commitment calculation using 3PL contracts, rate cards, inventory snapshots, receipts, putaway, storage positions, picks, packs, labor, value-added services, orders, invoices, and SLAs.","Produce a governed minimum commitment calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerFacility","3PL / Facility","text","Atlas Fulfillment / DFW-04"],["caseReference","Minimum commitment calculation Reference","text","3RO09-2026-001"],["billedAmount","3PL Billed Amount","currency",924000],["supportedAmount","Activity-Supported Amount","currency",811500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Ecommerce fulfillment center","Cold-storage warehouse","Retail distribution center","Spare parts 3PL","Omnichannel facility"]}),
feature("inventory-accuracy-sla","3RO10","Inventory accuracy SLA","Reconcile inventory accuracy sla using 3PL contracts, rate cards, inventory snapshots, receipts, putaway, storage positions, picks, packs, labor, value-added services, orders, invoices, and SLAs.","Produce a governed inventory accuracy sla decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerFacility","3PL / Facility","text","Atlas Fulfillment / DFW-04"],["caseReference","Inventory accuracy SLA Reference","text","3RO10-2026-001"],["billedAmount","3PL Billed Amount","currency",924000],["supportedAmount","Activity-Supported Amount","currency",811500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Ecommerce fulfillment center","Cold-storage warehouse","Retail distribution center","Spare parts 3PL","Omnichannel facility"]}),
feature("order-cutoff-and-fulfillment-sla","3RO11","Order cutoff and fulfillment SLA","Reconcile order cutoff and fulfillment sla using 3PL contracts, rate cards, inventory snapshots, receipts, putaway, storage positions, picks, packs, labor, value-added services, orders, invoices, and SLAs.","Produce a governed order cutoff and fulfillment sla decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerFacility","3PL / Facility","text","Atlas Fulfillment / DFW-04"],["caseReference","Order cutoff and fulfillment SLA Reference","text","3RO11-2026-001"],["billedAmount","3PL Billed Amount","currency",924000],["supportedAmount","Activity-Supported Amount","currency",811500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Ecommerce fulfillment center","Cold-storage warehouse","Retail distribution center","Spare parts 3PL","Omnichannel facility"]}),
feature("loss-and-damage-claims","3RO12","Loss and damage claims","Reconcile loss and damage claims using 3PL contracts, rate cards, inventory snapshots, receipts, putaway, storage positions, picks, packs, labor, value-added services, orders, invoices, and SLAs.","Produce a governed loss and damage claims decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerFacility","3PL / Facility","text","Atlas Fulfillment / DFW-04"],["caseReference","Loss and damage claims Reference","text","3RO12-2026-001"],["billedAmount","3PL Billed Amount","currency",924000],["supportedAmount","Activity-Supported Amount","currency",811500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Ecommerce fulfillment center","Cold-storage warehouse","Retail distribution center","Spare parts 3PL","Omnichannel facility"]}),
feature("invoice-recalculation","3RO13","Invoice recalculation","Reconcile invoice recalculation using 3PL contracts, rate cards, inventory snapshots, receipts, putaway, storage positions, picks, packs, labor, value-added services, orders, invoices, and SLAs.","Produce a governed invoice recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerFacility","3PL / Facility","text","Atlas Fulfillment / DFW-04"],["caseReference","Invoice recalculation Reference","text","3RO13-2026-001"],["billedAmount","3PL Billed Amount","currency",924000],["supportedAmount","Activity-Supported Amount","currency",811500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Ecommerce fulfillment center","Cold-storage warehouse","Retail distribution center","Spare parts 3PL","Omnichannel facility"]}),
feature("3pl-dispute-package","3RO14","3PL dispute package","Reconcile 3pl dispute package using 3PL contracts, rate cards, inventory snapshots, receipts, putaway, storage positions, picks, packs, labor, value-added services, orders, invoices, and SLAs.","Produce a governed 3pl dispute package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerFacility","3PL / Facility","text","Atlas Fulfillment / DFW-04"],["caseReference","3PL dispute package Reference","text","3RO14-2026-001"],["billedAmount","3PL Billed Amount","currency",924000],["supportedAmount","Activity-Supported Amount","currency",811500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Ecommerce fulfillment center","Cold-storage warehouse","Retail distribution center","Spare parts 3PL","Omnichannel facility"]}),
feature("credit-reconciliation","3RO15","Credit reconciliation","Reconcile credit reconciliation using 3PL contracts, rate cards, inventory snapshots, receipts, putaway, storage positions, picks, packs, labor, value-added services, orders, invoices, and SLAs.","Produce a governed credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerFacility","3PL / Facility","text","Atlas Fulfillment / DFW-04"],["caseReference","Credit reconciliation Reference","text","3RO15-2026-001"],["billedAmount","3PL Billed Amount","currency",924000],["supportedAmount","Activity-Supported Amount","currency",811500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Ecommerce fulfillment center","Cold-storage warehouse","Retail distribution center","Spare parts 3PL","Omnichannel facility"]}),
feature("facility-sku-and-activity-analytics","3RO16","Facility SKU and activity analytics","Reconcile facility sku and activity analytics using 3PL contracts, rate cards, inventory snapshots, receipts, putaway, storage positions, picks, packs, labor, value-added services, orders, invoices, and SLAs.","Produce a governed facility sku and activity analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerFacility","3PL / Facility","text","Atlas Fulfillment / DFW-04"],["caseReference","Facility SKU and activity analytics Reference","text","3RO16-2026-001"],["billedAmount","3PL Billed Amount","currency",924000],["supportedAmount","Activity-Supported Amount","currency",811500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Ecommerce fulfillment center","Cold-storage warehouse","Retail distribution center","Spare parts 3PL","Omnichannel facility"]})
]);
